//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBhavna.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBooking
    {
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public Nullable<decimal> Size { get; set; }
        public Nullable<decimal> Price { get; set; }
        public decimal TotalPrice { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Note { get; set; }
        public System.DateTime DeliveryDate { get; set; }
    }
}
