//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBhavna.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Type { get; set; }
        public string Flavour { get; set; }
        public string Size { get; set; }
        public decimal Amount { get; set; }
        public string Address { get; set; }
        public string Note { get; set; }
        public System.DateTime Delivery { get; set; }
        public string Img { get; set; }
    }
}
